### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by Agneli** [helloandre/playr#1]
@helloandre, firstly congratulations on your application.
I'm developing a OpenSource WebApp for Firefox OS to control a Linux remotely.
I wonder if you permit me to use parts of your code in my application (Show info of musics on WebApp).

Thank you in advance.

**Comment by helloandre** [comment]
You are of course permitted to do with it what you will.

However, this is 3 year old code. It hasn't been updated or even used since then. Express, Node, and Rhythmbox have all been updated significantly since then. 

I therefore recommend you take the concepts you want, but I would highly recommend against just dropping this into anything.

**Comment by Agneli** [comment]
Thank you very much @helloandre.
I am updating the necessary parts of the code.
When my App is ready I'll to return show you.

**Comment by Agneli** [comment]
Hi @helloandre.
As promised, here is the app.

https://github.com/Agneli/linux-remote-control

Thank you very much for your code!
